export const routes = {
  home: '/home',
  shop: '/shop',
  dish: '/dish',
  onboarding: '/',
  order: '/order',
  offers: '/offers',
  search: '/search',
  signIn: '/sign-in',
  signUp: '/sign-up',
  profile: '/profile',
  checkout: '/checkout',
  cartEmpty: '/cart-empty',
  myFavorite: '/my-favorite',
  editProfile: '/edit-profile',
  newPassword: '/new-password',
  orderFailed: '/order-failed',
  OrderSuccess: '/order-success',
  shopCategory: '/shop-category',
  orderHistory: '/order-history',
  myPromocodes: '/my-promocodes',
  forgotPassword: '/forgot-password',
  confirmationCode: '/confirmation-code',
  verifyYourPhoneNumber: '/verify-your-phone-number',
  forgotPasswordSentEmail: '/forgot-password-sent-email',
} as const;
